config/routes.rb
Imagina::Application.routes.draw do
  get "home/index"

  resources :comments

  resources :images

  root :to => 'home#index', as: 'Imagina'

end

app/models/comment.rb
#@author Oswaldo Didier Lopez Garcia
#24 de Agosto del 2012
#oswaldo@codetlan.com
class Comment < ActiveRecord::Base
  #Le decimos que los comentarios pertenecen a una imagen
  belongs_to :image
  #Hacemos accesibles los atributos del modelo para que se puedan crear nuevos comentarios
  attr_accessible :image_id, :text
end

app/models/image.rb
#@author Oswaldo Didier Lopez Garcia
#24 de Agosto del 2012
#oswaldo@codetlan.com
class Image < ActiveRecord::Base
  #Realizamos la relacion has many esto quiere decir que la Imagen tiene muchos comentarios
  has_many :comments
  #Hacemos accesibles los atributos del modelo para que se puedan crear nuevas imagenes
  attr_accessible :name, :picture
  #Declaramos que para el atributo picture del modelo imagen va montar un upload debido a que se estaran subiendo imagenes a la app
  mount_uploader :picture, PictureUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
#@author Oswaldo Didier Lopez Garcia
#24 de Agosto del 2012
#oswaldo@codetlan.com
class CommentsController < ApplicationController
  # GET /comments
  # GET /comments.json
  #Listamos los comentarios de acuerdo al id de la imagen en la que estemos posicionados
  # Nos regresa la respuesta en JS
  def index
    @comments = Comment.find_all_by_image_id(params[:id])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
      format.js
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  #Listamos los comentarios de acuerdo al id de la imagen en la que estemos posicionados
  def show
    @comments = Comment.find_all_by_image_id(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  # Nos regresa la respuesta en JS
  def new
    @comment = Comment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
      format.js
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  # Nos regresa la respuesta en JS
  def create
    @comment = Comment.new(params[:comment])

    respond_to do |format|
      if @comment.save
        #Buscamos y listamos todos los comentarios que tengan el image_id con el que fue agregado el comentario
        @comments = Comment.find_all_by_image_id(@comment.image_id)
        format.js
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  #Nos regresa una respuesta en JS
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    #Despues de eliminar buscamos y listamos todos los comentarios de acuerdo al image_id que eliminamos con la finalidad de
    #hacer un refrescado ajax
    @comments = Comment.find_all_by_image_id(@comment.image_id)

    respond_to do |format|
      format.js
    end
  end
end

app/controllers/home_controller.rb
#@author Oswaldo Didier Lopez Garcia
#24 de Agosto del 2012
#oswaldo@codetlan.com
class HomeController < ApplicationController
  #Este metodo se manda a llamar para el index que estamos mostrando en nuestra aplicacion y a su vez le debemos de
  #pasar la lista de imagenes, de comentarios y se crean los modelos imagenes y comentarios para poder mostrarlos en el index
  def index
    @images = Image.all
    @image = Image.new
    @comments = Comment.find_all_by_image_id(1)
    @comment = Comment.new
  end
end

app/controllers/images_controller.rb
#@author Oswaldo Didier Lopez Garcia
#24 de Agosto del 2012
#oswaldo@codetlan.com
class ImagesController < ApplicationController

  # GET /images/1
  # GET /images/1.json
  def show
    @image = Image.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @image }
    end
  end

  # GET /images/new
  # GET /images/new.json
  def new
    @image = Image.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @image }
      format.js
    end
  end

  # GET /images/1/edit
  def edit
    @image = Image.find(params[:id])
  end

  # POST /images
  # POST /images.json
  # Nos regresa la respuesta en JS
  def create
    @image = Image.new(params[:image])

    respond_to do |format|
      if @image.save
        format.js
      else
        format.js
      end
    end
  end

  # PUT /images/1
  # PUT /images/1.json
  def update
    @image = Image.find(params[:id])

    respond_to do |format|
      if @image.update_attributes(params[:image])
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image = Image.find(params[:id])
    @image.destroy

    respond_to do |format|
      format.html { redirect_to images_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/comments/_comments.html.erb
<h1>Comentarios</h1>

<div>
  <ol>
    <% @comments.each do |comment| %>
        <li>
          <div><font color="#ff8c00" size="3" style="background: #E0E0E0"><%= comment.text %></font></div>
          <!--<td><= link_to 'Show', comment %></td>
<td><= link_to 'Edit', edit_comment_path(comment) %></td>
<td><= link_to 'Destroy', comment, confirm: 'Are you sure?', method: :delete %></td>-->
        </li>
    <% end %>
  </ol>
</div>

app/views/comments/_form.html.erb
<!-- Formulario de comentarios  el cual tiene la propiedad de remote => true esto quiere decir que las llamadas seran remotas
     esto con el fin de realizar una llamada JS-->
<%= form_for @comment, :remote => true, :html => {:multipart => true, :class => 'form-inline' } do |f| %>
    <!-- Se pasa el id = 'form' el cual sera utilizado para limpiar el formulario con jquery vease create.js.erb -->
    <%= f.text_field :text, :id => 'form',  :class => 'input-medium', :placeholder => "Escribe..." %>

    <%= f.hidden_field :image_id, :id => "imagen"%>

    <%= f.submit '+', :remote => true, :class => 'btn-mini btn-info'%>
<% end %>

app/views/comments/create.js.erb
/*@author Oswaldo Didier Lopez Garcia
* 24 de Agosto del 2012
* oswaldo@codetlan.com */

 /* Este archivo se manda a llamar despues de agregar un comentario debido a que manda a llamar JS.
* Aqui vamos recargar los comentarios una vez que se agregue alguno y despues limpiamos el cuadro de texto por medio de un id*/
$("#comments").html("<%= escape_javascript(render :template => 'comments/index')%>");
$("#form").val("");

app/views/comments/destroy.js.erb
/*@author Oswaldo Didier Lopez Garcia
 * 24 de Agosto del 2012
 * oswaldo@codetlan.com */

 /* Archivo que se manda a llamar despues de eliminar un comentario.
* Listamos los comentarios que quedan en existencia*/
$("#comments").html("<%= escape_javascript(render :template => 'comments/index')%>");

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<!-- Template que lista los comentarios de acuerdo a la variable @comments que se crea en el controlador Comment y el metodo
     index, dicho metodo traera un arreglo de los comentarios que tiene la imagen-->
<h1>Comentarios</h1>

<div>
  <ol>
    <% @comments.each do |comment| %>
        <li>
          <div><font color="#ff8c00" size="3" style="background: #E0E0E0"><%= comment.text %></font>
            <%= link_to 'X', comment, :remote => true, method: :delete %></div>
        </li>
    <% end %>
  </ol>
</div>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
  <h1>Comentarios</h1>

  <div>
    <ol>
      <% @comments.each do |comment| %>
          <li>
            <div><font color="#ff8c00" size="3" style="background: #E0E0E0"><%= comment.text %></font>
              <%= link_to 'X', comment, :remote => true, method: :delete %></div>
          </li>
      <% end %>
    </ol>
  </div>

app/views/home/index.html.erb
<!-- Es el index que mostramos como pagina principal de nuestra sistema solo tiene un navbar y renderea el templete images/index
     en el cual esta construido el sistema -->
<div class="navbar-inner">
  <center><h1><font color="#708090">Imagina</font></h1></center>
</div>
<br>
<%= render :template => 'images/index' %>

app/views/images/_form.html.erb
<!-- Formulario de imagen  el cual tiene la propiedad de remote => true esto quiere decir que las llamadas seran remotas
     esto con el fin de realizar una llamada JS-->
<%= form_for @image, :remote => true, :html => {:multipart => true, :class => 'form-inline' } do |f| %>

    <%= f.text_field :name, :class => 'input-medium', :placeholder => "Nombre Imagen" %>

    <%= f.file_field :picture %>

    <%= f.submit 'Crear Imagen', :remote => true, :class => 'btn-medium btn-success' %>
<% end %>

app/views/images/create.js.erb
/*@author Oswaldo Didier Lopez Garcia
 * 24 de Agosto del 2012
 * oswaldo@codetlan.com */

 /* Para las imagenes se agrego una gema llamada remotipart la cual tiene la finalidad de cachar el tipo de respuesta
* que se obtenga al agregar la imagen de acuerdo a si los parametros trae o no trae imagen.*/
<% if remotipart_submitted? %>
//En caso de que traiga imagen se realiza una referencia al index.
location.href = '/';
<% else %>
//Validacion para que no agregue imagenes vacias.
<% end %>

app/views/images/edit.html.erb
<h1>Editing image</h1>

<%= render 'form' %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<!-- Columna vertebral de nuestro sistema en el cual se muestra el carousel, renderiamos el formulario de imagenes y comentarios
     y listamos los comentarios-->
<div><%= render :partial => 'images/form' %></div><!-- Rendereamos nuestro formulario para la creacion de imagenes -->
<div class="row-fluid">
  <div class="span8 columns">
    <!-- Carousel de imagenes y le ponemos un id el cual ocupamos en el archivo application.js para escuchar el evento click de las
         imagenes y con esto mostrar sus comentarios para cada una de ellas-->
    <div id="myCarousel" class="carousel">
      <div class="carousel-inner">
        <% i = 0 %>
        <% @images.each do |image| %>
            <% if i == 0 %>
                <div class="active item">
                  <% i=1 %>
            <% else %>
                <div class="item">
            <% end %>
            <center>
              <%= image_tag image.picture_url, :id => image.id %>
              <a class="carousel-control left">&lsaquo;</a>
              <a class="carousel-control right">&rsaquo;</a></center>
            </div>
        <% end %>

        </div>
      </div>
    </div>

  <br/>
  <!-- Listamos los comentarios y rendereamos el form.
       Asignamos un id al div el cual utilizaremos para actualizar los
       comentarios en el caso de agregar o eliminar algunos de estos-->
  <div class="span3">
    <div id="comments"><%= render :template => 'comments/index' %></div>
    <div><%= render :partial => 'comments/form' %></div>
  </div>

app/views/images/new.html.erb
<h1>New image</h1>

<%= render 'form' %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @image.name %>
</p>

<p>
  <b>Picture:</b>
  <%= @image.picture %>
</p>


<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Imagina</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <%= yield %>
</div>

</body>
</html>